import { Inter } from "next/font/google";
//import "./globals.css";

import HeaderPage from "./Components/WebTemplate/HeaderPage";
import FooterPage from "./Components/WebTemplate/FooterPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div><HeaderPage /></div>
        <div>
          <hr />{children}<hr />
        </div>
        <div><FooterPage /></div>

      </body>
    </html>
  );
}
